train_file: ["/data1/yaxiong/dataset/DGM4/metadata_split/guardian/train.json"]
val_file: ["/data1/yaxiong/dataset/DGM4/metadata_split/guardian/val.json"]


bert_config: 'configs/config_bert.json'
image_res: 224
batch_size_train: 2
batch_size_val: 1
max_words: 50








